spring:
  application:
    name: krushak-config-server
  profiles:
    active: dev
  cloud:
    config:
      profile: git
      server:
        git:
          uri: https://github.com/bgandluru/krushak.git
          default-label: master
          clone-submodules: true
          search-paths: krushak-config
          clone-on-start: true
server:
  port: 8001

#Adding eureka registry service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true